apiVersion: v1
kind: Pod
metadata:
  labels:
    name: server1-ve-56377f29-e603-11ee-a122-179ee4765847
    owner: touchstone
    request_host: touchstone-portal-07-12-2022-012311
    request_user: root
    role: server
  name: server1-ve-56377f29-e603-11ee-a122-179ee4765847
  namespace: default
spec:
  containers:
  - image: voereir/touchstone-server-ubuntu:v3.11.1
    imagePullPolicy: IfNotPresent
    name: container-server1-ve-56377f29-e603-11ee-a122-179ee4765847
    resources:
      limits:
        cpu: "4"
        memory: "4000Mi"
      requests:
        cpu: "4"
        memory: "4000Mi"
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - CAP_SYS_NICE
          - SYS_NICE
          - IPC_LOCK
          - NET_ADMIN
          - SYS_TIME
          - CAP_NET_RAW
          - CAP_BPF
          - CAP_SYS_ADMIN
          - SYS_ADMIN
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules-qidut
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-w7kzf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ubuntu-md-0-gv8qv-vffht-4kgdj
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules-qidut
  - name: kube-api-access-w7kzf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace